'use client';

import Link from 'next/link';
import { ChevronDownIcon, ChevronUpIcon } from '@radix-ui/react-icons';
import { useState, useEffect } from 'react';

interface FAQItem {
  id: string;
  question: string;
  answer: string;
  category: string;
}

const faqData: FAQItem[] = [
  // General Questions
  {
    id: 'what-is-essayy',
    question: 'What is Essayy and how does it work?',
    answer: 'Essayy is an AI-powered essay writing platform that helps students and professionals create high-quality essays, research papers, and academic content. Our AI analyzes your topic, requirements, and preferred style to generate well-structured, original content that meets academic standards.',
    category: 'General'
  },
  {
    id: 'is-essayy-free',
    question: 'Is Essayy free to use?',
    answer: 'Essayy offers both free and premium plans. Our free plan includes basic essay generation with limited features. Premium plans provide unlimited essays, advanced AI models, plagiarism checking, citation generation, and priority support.',
    category: 'General'
  },
  {
    id: 'essay-quality',
    question: 'How good is the quality of AI-generated essays?',
    answer: 'Our AI generates high-quality, coherent essays that follow proper academic structure. The content is original, well-researched, and tailored to your specific requirements. However, we recommend reviewing and editing the generated content to ensure it meets your exact needs.',
    category: 'General'
  },
  
  // Essay Generation
  {
    id: 'essay-types',
    question: 'What types of essays can Essayy generate?',
    answer: 'Essayy can generate various essay types including argumentative, persuasive, analytical, narrative, descriptive, expository, compare and contrast, cause and effect essays, research papers, and college application essays.',
    category: 'Essay Generation'
  },
  {
    id: 'essay-length',
    question: 'How long can the generated essays be?',
    answer: 'Essay length varies by plan. Free users can generate essays up to 500 words, while premium users can create essays ranging from 250 to 5000+ words. You can specify your desired word count when generating an essay.',
    category: 'Essay Generation'
  },
  {
    id: 'topic-requirements',
    question: 'What information do I need to provide for essay generation?',
    answer: 'To generate an essay, you need to provide: the essay topic or prompt, essay type (argumentative, persuasive, etc.), desired length, academic level, and any specific requirements or instructions. The more details you provide, the better the AI can tailor the content.',
    category: 'Essay Generation'
  },
  {
    id: 'generation-time',
    question: 'How long does it take to generate an essay?',
    answer: 'Essay generation typically takes 30 seconds to 2 minutes, depending on the length and complexity of your requirements. Longer essays and more detailed requirements may take slightly more time.',
    category: 'Essay Generation'
  },
  
  // AI Humanizer
  {
    id: 'what-is-humanizer',
    question: 'What is the AI Humanizer feature?',
    answer: 'The AI Humanizer transforms AI-generated text to make it sound more natural and human-like. It adjusts sentence structure, vocabulary, and writing style to reduce the detectability of AI-generated content while maintaining the original meaning.',
    category: 'AI Humanizer'
  },
  {
    id: 'why-humanize',
    question: 'Why should I humanize my AI-generated content?',
    answer: 'Humanizing AI content helps it pass AI detection tools, makes it sound more natural and engaging, improves readability, and ensures it aligns with human writing patterns that readers expect.',
    category: 'AI Humanizer'
  },
  {
    id: 'humanizer-accuracy',
    question: 'How effective is the AI Humanizer?',
    answer: 'Our AI Humanizer is highly effective at making content sound natural while preserving the original meaning. It significantly reduces AI detection scores and improves the overall quality and readability of the text.',
    category: 'AI Humanizer'
  },
  
  // AI Detection & Plagiarism
  {
    id: 'ai-detection',
    question: 'Can you detect if content is AI-generated?',
    answer: 'Yes, our AI Content Detector can identify whether text was likely generated by AI tools. It provides a confidence score and highlights potentially AI-generated sections, helping you understand how detectable your content might be.',
    category: 'AI Detection'
  },
  {
    id: 'plagiarism-checker',
    question: 'Does Essayy check for plagiarism?',
    answer: 'Yes, our premium plans include a built-in plagiarism checker that scans your content against billions of web pages and academic databases to ensure originality. It provides detailed reports highlighting any potential matches.',
    category: 'AI Detection'
  },
  {
    id: 'originality-guarantee',
    question: 'Is the generated content original and plagiarism-free?',
    answer: 'Yes, our AI generates original content based on your specific requirements. However, we recommend using our plagiarism checker to verify originality, especially for academic submissions.',
    category: 'AI Detection'
  },
  
  // Citations & References
  {
    id: 'citation-styles',
    question: 'What citation styles does Essayy support?',
    answer: 'Essayy supports all major citation styles including APA, MLA, Chicago, Harvard, IEEE, and many others. Our citation generator automatically formats your references according to the selected style guide.',
    category: 'Citations'
  },
  {
    id: 'auto-citations',
    question: 'Does the AI automatically add citations to essays?',
    answer: 'Yes, when generating essays, our AI can automatically include relevant citations and create a bibliography in your preferred citation style. You can also use our separate citation generator for manual reference creation.',
    category: 'Citations'
  },
  {
    id: 'citation-accuracy',
    question: 'How accurate are the generated citations?',
    answer: 'Our citation generator follows official style guide rules and is highly accurate. However, we recommend double-checking citations against the official style manuals, especially for important academic work.',
    category: 'Citations'
  },
  
  // Academic Integrity
  {
    id: 'academic-integrity',
    question: 'Is using AI for essays considered cheating?',
    answer: 'This depends on your institution\'s policies. We recommend using Essayy as a research and brainstorming tool to help you understand topics and structure your thoughts. Always check your school\'s academic integrity policies and use our tools responsibly.',
    category: 'Academic Integrity'
  },
  {
    id: 'ethical-use',
    question: 'How should I ethically use AI writing tools?',
    answer: 'Use AI tools for research, brainstorming, and understanding topics. Review and edit generated content, add your own insights, verify facts, and always follow your institution\'s guidelines. Consider AI as a writing assistant, not a replacement for your own thinking.',
    category: 'Academic Integrity'
  },
  {
    id: 'teacher-detection',
    question: 'Will my teacher know I used AI?',
    answer: 'AI detection tools are becoming more common in educational settings. We recommend being transparent about AI use when required by your institution and using our humanizer feature to make content sound more natural.',
    category: 'Academic Integrity'
  },
  
  // Technical & Account
  {
    id: 'account-creation',
    question: 'Do I need to create an account to use Essayy?',
    answer: 'You can try our basic features without an account, but creating a free account gives you access to more features, saves your essay history, and allows you to upgrade to premium plans.',
    category: 'Account'
  },
  {
    id: 'data-privacy',
    question: 'Is my data safe and private?',
    answer: 'Yes, we take data privacy seriously. Your essays and personal information are encrypted and stored securely. We don\'t share your content with third parties, and you can delete your data at any time.',
    category: 'Account'
  },
  {
    id: 'supported-languages',
    question: 'What languages does Essayy support?',
    answer: 'Currently, Essayy primarily supports English essay generation. We\'re working on adding support for other languages in future updates.',
    category: 'Technical'
  },
  {
    id: 'mobile-support',
    question: 'Can I use Essayy on my mobile device?',
    answer: 'Yes, Essayy is fully responsive and works on all devices including smartphones, tablets, and desktop computers. You can access all features through your mobile browser.',
    category: 'Technical'
  },
  
  // Pricing & Plans
  {
    id: 'pricing-plans',
    question: 'What are the different pricing plans?',
    answer: 'We offer a free plan with basic features and several premium plans with unlimited essays, advanced AI models, plagiarism checking, and priority support. Visit our pricing page for detailed information.',
    category: 'Pricing'
  },
  {
    id: 'upgrade-benefits',
    question: 'What are the benefits of upgrading to premium?',
    answer: 'Premium plans include unlimited essay generation, longer word limits, advanced AI models, plagiarism checking, citation generation, AI humanizer, priority support, and export options (PDF, Word).',
    category: 'Pricing'
  },
  {
    id: 'refund-policy',
    question: 'Do you offer refunds?',
    answer: 'We offer a satisfaction guarantee. If you\'re not happy with our service within the first 7 days of your premium subscription, contact our support team for a full refund.',
    category: 'Pricing'
  },
  
  // Support
  {
    id: 'customer-support',
    question: 'How can I get help or support?',
    answer: 'You can contact our support team through the contact form on our website, email us directly, or use the live chat feature (premium users). We typically respond within 24 hours.',
    category: 'Support'
  },
  {
    id: 'technical-issues',
    question: 'What should I do if I encounter technical issues?',
    answer: 'If you experience technical problems, try refreshing the page or clearing your browser cache. If issues persist, contact our support team with details about the problem and your browser/device information.',
    category: 'Support'
  }
];

const categories = Array.from(new Set(faqData.map(item => item.category)));

function FAQAccordion({ item }: { item: FAQItem }) {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <div className="border border-gray-200 rounded-lg mb-4">
      <button
        className="w-full px-6 py-4 text-left flex justify-between items-center hover:bg-gray-50 transition-colors"
        onClick={() => setIsOpen(!isOpen)}
      >
        <h3 className="text-lg font-semibold text-gray-900">{item.question}</h3>
        {isOpen ? (
          <ChevronUpIcon className="h-5 w-5 text-gray-500 flex-shrink-0" />
        ) : (
          <ChevronDownIcon className="h-5 w-5 text-gray-500 flex-shrink-0" />
        )}
      </button>
      {isOpen && (
        <div className="px-6 pb-4">
          <p className="text-gray-700 leading-relaxed">{item.answer}</p>
        </div>
      )}
    </div>
  );
}

export default function FAQPage() {
  const [selectedCategory, setSelectedCategory] = useState<string>('All');
  
  const filteredFAQs = selectedCategory === 'All' 
    ? faqData 
    : faqData.filter(item => item.category === selectedCategory);

  // Set document title and meta tags
  useEffect(() => {
    document.title = 'Frequently Asked Questions - Essayy AI Essay Writer';
    
    // Update meta description
    const metaDescription = document.querySelector('meta[name="description"]');
    if (metaDescription) {
      metaDescription.setAttribute('content', 'Find answers to common questions about Essayy AI essay writer, humanizer, plagiarism checker, and citation generator. Get help with our AI writing tools.');
    }
    
    // Update keywords
    const metaKeywords = document.querySelector('meta[name="keywords"]');
    if (metaKeywords) {
      metaKeywords.setAttribute('content', 'FAQ, AI essay writer questions, essay generator help, AI humanizer FAQ, plagiarism checker questions, citation generator help');
    }
  }, []);

  return (
    <div className="min-h-screen bg-white">
      {/* Hero Section */}
      <div className="bg-gradient-to-br from-blue-50 to-indigo-100 py-16">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h1 className="text-4xl font-bold text-gray-900 mb-4">
            Frequently Asked Questions
          </h1>
          <p className="text-xl text-gray-600 mb-8">
            Find answers to common questions about Essayy AI essay writer, features, and services
          </p>
          <div className="bg-white p-6 rounded-lg shadow-sm border">
            <p className="text-gray-700 mb-4">
              Can't find what you're looking for? 
            </p>
            <Link 
              href="/contact"
              className="inline-flex items-center px-6 py-3 bg-blue-600 text-white font-medium rounded-lg hover:bg-blue-700 transition-colors"
            >
              Contact Support
            </Link>
          </div>
        </div>
      </div>

      {/* FAQ Content */}
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        {/* Category Filter */}
        <div className="mb-8">
          <h2 className="text-2xl font-bold text-gray-900 mb-4">Browse by Category</h2>
          <div className="flex flex-wrap gap-2">
            <button
              onClick={() => setSelectedCategory('All')}
              className={`px-4 py-2 rounded-full text-sm font-medium transition-colors ${
                selectedCategory === 'All'
                  ? 'bg-blue-600 text-white'
                  : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
              }`}
            >
              All ({faqData.length})
            </button>
            {categories.map(category => (
              <button
                key={category}
                onClick={() => setSelectedCategory(category)}
                className={`px-4 py-2 rounded-full text-sm font-medium transition-colors ${
                  selectedCategory === category
                    ? 'bg-blue-600 text-white'
                    : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                }`}
              >
                {category} ({faqData.filter(item => item.category === category).length})
              </button>
            ))}
          </div>
        </div>

        {/* FAQ Items */}
        <div className="space-y-2">
          {filteredFAQs.map(item => (
            <FAQAccordion key={item.id} item={item} />
          ))}
        </div>

        {/* Additional Help Section */}
        <div className="mt-16 bg-gray-50 rounded-lg p-8 text-center">
          <h2 className="text-2xl font-bold text-gray-900 mb-4">
            Still Have Questions?
          </h2>
          <p className="text-gray-600 mb-6">
            Our support team is here to help you get the most out of Essayy
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link
              href="/contact"
              className="inline-flex items-center px-6 py-3 bg-blue-600 text-white font-medium rounded-lg hover:bg-blue-700 transition-colors"
            >
              Contact Support
            </Link>
            <Link
              href="/features"
              className="inline-flex items-center px-6 py-3 border border-gray-300 text-gray-700 font-medium rounded-lg hover:bg-gray-50 transition-colors"
            >
              Explore Features
            </Link>
          </div>
        </div>

        {/* Quick Links */}
        <div className="mt-12 grid md:grid-cols-3 gap-6">
          <div className="text-center">
            <h3 className="text-lg font-semibold text-gray-900 mb-2">Getting Started</h3>
            <p className="text-gray-600 text-sm mb-3">
              New to Essayy? Learn the basics
            </p>
            <Link href="/features/essay-writer" className="text-blue-600 hover:text-blue-700 text-sm font-medium">
              Start Writing Essays →
            </Link>
          </div>
          <div className="text-center">
            <h3 className="text-lg font-semibold text-gray-900 mb-2">Advanced Features</h3>
            <p className="text-gray-600 text-sm mb-3">
              Explore AI humanizer and detection
            </p>
            <Link href="/features/ai-humanizer" className="text-blue-600 hover:text-blue-700 text-sm font-medium">
              Try AI Humanizer →
            </Link>
          </div>
          <div className="text-center">
            <h3 className="text-lg font-semibold text-gray-900 mb-2">Pricing & Plans</h3>
            <p className="text-gray-600 text-sm mb-3">
              Choose the right plan for you
            </p>
            <Link href="/pricing" className="text-blue-600 hover:text-blue-700 text-sm font-medium">
              View Pricing →
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
} 